apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: read-write-binding
  namespace: cp1
roleRef:
  kind: Role
  name: read-write
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: rakib
    apiGroup: rbac.authorization.k8s.io