apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: superuser-binding
  namespace: cp1
roleRef:
  kind: ClusterRole
  name: superuser
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: superuser
    apiGroup: rbac.authorization.k8s.io