apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-main-app
  labels:
    app: kube-main-app
  namespace: cp1
spec:
  replicas: 1
  template:
    metadata:
      name: kube-main-app
      labels:
        app: kube-main-app
    spec:
      serviceAccountName: dev-deployment-service-account
      containers:
        - name: kube-main-app
          image: jahadulrakib/kube-main-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: "Some"
            - name: CHILD_URL
              valueFrom:
                configMapKeyRef:
                  key: CHILD_URL
                  name: env-map-service
          volumeMounts:
            - name: data
              mountPath: /main-app
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: test-pvc-two
  selector:
    matchLabels:
      app: kube-main-app
