apiVersion: v1
kind: Service
metadata:
  name: child-app-service
  namespace: cp1
spec:
  selector:
    app: kube-child-app
  ports:
    - name: http-rest
      port: 80
      protocol: TCP
      targetPort: 8081
  type: ClusterIP
