apiVersion: v1
kind: Service
metadata:
  name: main-app-service
  namespace: cp1
spec:
  selector:
    app: kube-main-app
  ports:
    - name: http-rest
      port: 80
      protocol: TCP
      targetPort: 8080
  type: ClusterIP