apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-only
  namespace: cp1
rules:
  - apiGroups:
      - ""
    resources: [ "*" ]
    verbs:
      - get
      - list
      - watch