apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: superuser
  namespace: cp1
rules:
  - apiGroups:
      - ""
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete