apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: cp1
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      serviceAccountName: dev-deployment-service-account
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: mongo-vol
              mountPath: /mongodb
  volumeClaimTemplates:
    - metadata:
        name: mongo-vol
      spec:
        #volumeMode: Filesystem #Block/Filesystem
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: test-sc
