apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-4
  namespace: cp1
spec:
  storageClassName: test-sc
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/data/test_pv"