apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-5
  namespace: cp1
spec:
  storageClassName: test-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #Delete/Retain/Recycle
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp"