apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-1
  namespace: cp1
spec:
  storageClassName: test-sc
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/data/test_pv_1"