apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: cp1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: test-sc
  selector:
    matchLabels:
      type: test-pv-selector