apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-one
  namespace: cp1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: test-sc
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi