apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-sc
  namespace: cp1
provisioner: docker.io/hostpath
reclaimPolicy: Retain #Retain/Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate #Immediate/WaitForFirstConsumer
